# Generated by Django 5.2.5 on 2025-09-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_paid",
            field=models.BooleanField(
                default=False, verbose_name="Публикация публична"
            ),
        ),
    ]
