# Generated by Django 5.2.5 on 2025-09-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_paid_subscription",
            field=models.BooleanField(default=False, verbose_name="Подписка"),
        ),
    ]
