# Generated by Django 5.2.5 on 2025-09-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_has_paid_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/", verbose_name="Изображение"
            ),
        ),
    ]
